name: Publish gem

on:
  push:
    branches: [main]

jobs:
  publish:
    name: Build and publish gem
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.0.6"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Publish gem to Gh packages and RubyGems
        uses: dawidd6/action-publish-gem@v1
        with:
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
          github_token: ${{secrets.GITHUB_TOKEN}}
