name: Publish gem

on:
  pull_request:
    branches: [main]

jobs:
  publish:
    name: Build and publish gem
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "3.0.6"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gem_file=$(find . -maxdepth 1 -name "*.gem")
          gem push --key github --host https://rubygems.pkg.github.com/juliocabrera820 $gem_file

      - name: Publish to RubyGems
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          gem build convenlu.gemspec
          gem push *.gem
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
